/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author DELL
 */
public class View_Message1 extends javax.swing.JPanel {

    /**
     * Creates new form View_Message
     */
        public void loadStock() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dNow = sdf.format(new Date());
        
            ResultSet rs = MySQL.search("SELECT `stock`.`exd`,`stock`.`mfd`,`stock`.`id`,`product`.`id` ,`category`.`name` ,`brand`.`name`,`product`.`name`,`stock`.`qty`,`unit_of_mass`.`name` FROM `stock` INNER JOIN `grn_item` ON `grn_item`.`stock_id`=`stock`.`id` INNER JOIN `product` ON `stock`.`product_id` =`product`.id INNER JOIN `brand` ON `product`.`brand_id` =`brand`.`id` INNER JOIN `category` ON `product`.`category_id` =`category`.id \n"
                    + "INNER JOIN `unit_of_mass` ON `unit_of_mass`.`id`=`stock`.`unit_of_mass_id` WHERE `exd` <= ('" + dNow + "'  + INTERVAL 30 DAY)");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("stock.id"));
              
                v.add(rs.getString("category.name"));
                v.add(rs.getString("brand.name"));
                v.add(rs.getString("product.name"));
                v.add(rs.getString("stock.qty"));
                v.add(rs.getString("unit_of_mass.name"));
                v.add(rs.getString("stock.mfd"));
                v.add(rs.getString("stock.exd"));
                
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
           
        }
    }

    public View_Message1() {
        initComponents();
        loadStock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(770, 920));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Expiring Products");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock Id", "Category", "Brand", "Product Name", "Quantity", "Unit Of Mass", "Mfd", "Exd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(127, 127, 127)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

//        if (evt.getClickCount() == 1) {
//            int r = jTable1.getSelectedRow();
//            if (r == -1) {
//                JOptionPane.showMessageDialog(this, "Please select a Row", "Warning", JOptionPane.WARNING_MESSAGE);
//
//            } else {
//
//                String sid = jTable1.getValueAt(r, 0).toString();
//                String pname = jTable1.getValueAt(r, 4).toString();
//                String qty = jTable1.getValueAt(r, 5).toString();
//                String mass = jTable1.getValueAt(r, 6).toString();
//                try {
//                    ResultSet rs = MySQL.search("SELECT  product.name AS pname , stock.qty , unit_of_mass.name AS mass_name,suppliers.fname,suppliers.lname,suppliers.contact_no,supplier_shop.name,supplier_shop.contact_no AS shop_contact\n"
//                        + "FROM stock INNER JOIN grn_item ON  grn_item.stock_id=stock.id INNER JOIN grn ON grn.id=grn_item.grn_id INNER JOIN suppliers ON  suppliers.id=grn.suppliers_id \n"
//                        + "INNER JOIN supplier_shop ON supplier_shop.id =suppliers.supplier_shop_id INNER JOIN  unit_of_mass ON  unit_of_mass.id=stock.unit_of_mass_id INNER JOIN \n"
//                        + "product ON product.id=stock.product_id WHERE `stock`.`id`='" + sid + "' ORDER BY `stock`.`id`ASC ");
//                    rs.next();
//                    String supplier_fname = rs.getString("fname");
//                    String supplier_lname = rs.getString("lname");
//                    String supplier_shop = rs.getString("name");
//                    String supplier_contact = rs.getString("contact_no");
//                    String shop_contact = rs.getString("shop_contact");
//                    Home h = new Home();
//                    h.resize(1920, 1080);
//                    this.resize(770, 920);
//                    jLabel10.setText(pname);
//                    jLabel12.setText(supplier_fname + " " + supplier_lname);
//                    jLabel14.setText(supplier_shop);
//                    jLabel11.setText(qty + " " + mass);
//                    jLabel13.setText(supplier_contact);
//                    jLabel15.setText(shop_contact);
//
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
//
//            }
//        }

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
